### ISSUE TITLE
Can't be installed on windows with pip.

### ISSUE THREAD

**Issue by ShiboXuZJU** [riverlane/pauli_lcu#4]
The source C file seems to rely on many C99 features which is not friendly to MSVC. 
I have to rewrite them as cpp style and finally it works.
The program speed is impressively fast!

**Comment by christoph-riverlane** [comment]
Thank you for your interest in our software package!

As you say, the problem is that Microsoft chooses not to support complex numbers in C properly according to the standard (see https://learn.microsoft.com/en-us/cpp/c-runtime-library/complex-math-support?view=msvc-170).
At the moment we don't want to change the C code to support Microsoft-specific behaviour.

For Windows users, we suggest using WSL; we have tested the package on Windows using WSL and had no problems installing it with pip as in the README.

**Comment by ShiboXuZJU** [comment]
I see. Thanks for suggestions!
